'use strict';

// Regenerated by scripts/release.sh on every release -- do not hand-edit.
// This is the bare incrementing integer from the repo root's VERSION
// file, baked into the build so a running app knows its own version
// without reading anything off disk. See releasePointer.js for what
// it's compared against.
module.exports = { APP_VERSION: 10 };
