#!/bin/bash
# Builds Print Catalog, bumps its version, and publishes a GitHub
# Release with the built artifact attached -- this is the one command
# to run whenever you intend to ship to the loaner laptops. Run from
# the repo root (uses relative paths throughout) with a clean working
# tree, on the branch you actually want to release.
#
# Requires: gh CLI, authenticated with push access to this repo and
# permission to create releases (`gh auth status` to check).
#
# What "version" means here: a plain incrementing integer, written to
# both VERSION (repo root, for this script's own bookkeeping) and
# src/main/version.js (baked into the build so a running app knows its
# own version -- see releasePointer.js). Separate from package.json's
# semver string, which this script also keeps in sync purely because
# electron-builder reads it for artifact filenames.
#
# The data-repo release pointer ({version, releaseUrl} at PrintCat-
# data's root) is NOT written here -- the app itself updates that,
# the first time any laptop running a newer build than the pointer
# records enters edit mode (see main.js's enterEditSession() and
# releasePointer.js). This script's only job is to get a release
# artifact onto GitHub at a predictable URL for the app to find.

set -euo pipefail

cd "$(dirname "$0")/.."

if [ -n "$(git status --porcelain)" ]; then
  echo "Working tree isn't clean -- commit or stash first." >&2
  exit 1
fi

# 1. Bump version
OLD_VERSION=$(cat VERSION)
NEW_VERSION=$((OLD_VERSION + 1))
echo "$NEW_VERSION" > VERSION
echo "Bumping v$OLD_VERSION -> v$NEW_VERSION"

# 2. Bake the version into the build. Two places, same number:
# package.json (electron-builder's own artifact-filename source) and
# src/main/version.js (what the running app actually reads -- see
# releasePointer.js).
node -e "
  const fs = require('fs');
  const pkg = JSON.parse(fs.readFileSync('package.json'));
  pkg.version = '$NEW_VERSION.0.0';
  fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
"
cat > src/main/version.js << VERSION_EOF
'use strict';

// Regenerated by scripts/release.sh on every release -- do not hand-edit.
// This is the bare incrementing integer from the repo root's VERSION
// file, baked into the build so a running app knows its own version
// without reading anything off disk. See releasePointer.js for what
// it's compared against.
module.exports = { APP_VERSION: $NEW_VERSION };
VERSION_EOF

# 3. Generate release notes from commits since the last tag.
# %s%n%n%b%n = subject, blank line, full body, trailing blank line --
# deliberately generous with blank lines (git log then adds its own
# separator between commit entries), since sparse-but-clear beats
# run-together here.
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
if [ -n "$LAST_TAG" ]; then
  NOTES=$(git log "$LAST_TAG"..HEAD --pretty=format:'- %s%n%n%b%n')
else
  NOTES=$(git log --pretty=format:'- %s%n%n%b%n')
fi

# 4. Package. electron-builder's mac target list (dmg + zip, see
# package.json) produces both a normal installer for manual use and a
# zip for the update flow to fetch/unzip programmatically. Cleaned
# first so dist/ never accumulates old .dmg/.zip files across releases.
npm run clean
npm run dist

# Match on the version string we just baked into package.json, rather
# than trusting find's (filesystem-order-dependent) listing order --
# a stale zip left in dist/ from a previous run could otherwise get
# picked up silently. Not alphabetical-last either: once versions hit
# double digits that sorts wrong ("...-10.0.0-..." < "...-9.0.0-..."
# as strings). Excludes our own stable-named output pattern too, in
# case a previous run's renamed copy is still sitting in dist/ from an
# interrupted release. Fails loudly rather than guessing if there's no
# match -- better to stop here than tag a release with the wrong build.
BUILT_ZIP=$(find dist -maxdepth 1 -name "*.zip" ! -name "PrintCat-v*.zip" | grep -F -- "$NEW_VERSION.0.0" | head -n 1)
if [ -z "$BUILT_ZIP" ]; then
  echo "No .zip artifact matching version $NEW_VERSION.0.0 found in dist/ -- check electron-builder's mac.target config, or clear stale files from dist/." >&2
  exit 1
fi

# electron-builder's own zip filename (productName + version + "-mac",
# e.g. "Print Catalog-14.0.0-mac.zip") isn't something releasePointer.js
# should have to know or guess -- renaming to a stable, predictable name
# here means the app can construct its own download URL later with no
# GitHub API call at all. If this naming convention ever changes, it
# has to change in releasePointer.js's buildReleaseUrl() too.
RELEASE_ASSET="dist/PrintCat-v$NEW_VERSION.zip"
cp "$BUILT_ZIP" "$RELEASE_ASSET"

# 5. Commit the version bump
git add VERSION package.json src/main/version.js
git commit -m "Bump version to v$NEW_VERSION"
git push

# 6. Tag + release, with the generated notes
gh release create "v$NEW_VERSION" "$RELEASE_ASSET" \
  --title "v$NEW_VERSION" \
  --notes "$NOTES"

echo ""
echo "Release v$NEW_VERSION published. Any laptop that enters edit mode"
echo "will now update the data repo's release pointer on its own."
